import './globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getUser } from '../database/users';
import { LogoutButton } from './(auth)/logout/LogoutButton';
import { ApolloClientProvider } from './ApolloClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Task: Protect the dashboard page and redirect to login if the user is not logged in

  // 1. Checking if the sessionToken cookie exists
  const sessionCookie = cookies().get('sessionToken');

  // 2. Get the current logged in user from the database using the sessionToken value
  const user = sessionCookie && (await getUser(sessionCookie.value));

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>
            <Link href="/">Home</Link>
            <Link href="/animals">Animals</Link>
            <Link href="/animals/dashboard">Animal Dashboard</Link>
            <Link href="/notes">Notes</Link>
          </div>

          <div>{user?.username}</div>
          {user?.username ? (
            <LogoutButton />
          ) : (
            <>
              <Link href="/register">Register</Link>
              <Link href="/login">Login</Link>
            </>
          )}
        </nav>
        <ApolloClientProvider>
          <main>{children}</main>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
